site_name: LeviLamina
repo_url: https://github.com/LiteLDev/LeviLamina

nav:
  - Home: index.md

  - Install:
    - Windows: install_windows.md

  - Usage: usage.md

  - FAQ: faq.md

  - Native APIs: api/native

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  favicon: img/favicon.ico
  logo: img/logo.svg
  palette:
    primary: white

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc
  - tables
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist

plugins:
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          
        - locale: zh
          name: 中文
          nav_translations:
            FAQ: 常见问题
            Home: 主页
            Install: 安装
            Native APIs: 原生API
            Overview: 概述
            Usage: 使用



