on:
  push:
    paths:
      - scripts/localbdslibrary.lua
      - src
      - xmake.lua
  pull_request:
    paths:
      - scripts/localbdslibrary.lua
      - src
      - xmake.lua
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v3
        with:
          path: |
            ~/AppData/Local/.xmake
            .xmake
          key: ${{ runner.os }}-xmake-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-xmake-

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y --ccache=n

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v3
        with:
          name: liteloader-${{ github.sha }}-windows-amd64
          path: |
            build/windows/x64/release/LiteLoader.dll
            build/windows/x64/release/LiteLoader.lib
            build/windows/x64/release/LiteLoader.pdb
