on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          pip install -r requirements.txt
      - run: |
          mkdocs build
      - uses: actions/upload-pages-artifact@v2
        with:
          path: site/

  deploy:
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push' # For development only
    needs: build
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v2
